-keep class com.yausername.youtubedl_android.** { *; }
-dontwarn com.yausername.youtubedl_android.**
-keep class io.github.junkfood02.youtubedl_android.** { *; }
-dontwarn io.github.junkfood02.youtubedl_android.**
